In [1]:
import numpy as np

import torch

In [3]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
nums = torch.arange(9)
nums

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
nums.shape

torch.Size([9])

In [9]:
type(nums)

torch.Tensor

In [10]:
nums.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [13]:
arr_torch = torch.from_numpy(arr)
arr_torch

tensor([1, 2, 3])

In [14]:
arr_torch.float()

tensor([1., 2., 3.])

In [16]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [17]:
arr_torch.to(device)

tensor([1, 2, 3], device='cuda:0')

## AutoGrad

In [18]:
x = torch.ones(2, 2, requires_grad=True)

In [19]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [21]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [22]:
print(y.grad_fn)

In [23]:
z = y * y * 3
out = z.mean()

In [24]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [26]:
out.backward()

In [27]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [31]:
print((x**2).requires_grad)

True


In [30]:
with torch.no_grad():
    print((x**2).requires_grad)

False
